### ISSUE TITLE
Improve Compatibility Information

### ISSUE THREAD

**Issue by twiro** [domsammut/freegeoip_service#1]
Hey Dom,

thank you for this nice extension! Just tested it in an 2.6.7 install and it works as expected - It would be cool if you could set a `max`-value of `2.X.X` to the latest release in your `extension.meta.xml`. That way [symphonyextensions.com](http://symphonyextensions.com/extensions/freegeoip_service/) will actually be able to show the compatibility information  correctly.

And as there should happen no breaking changes in any upcoming Symphony 2.X release it's pretty safe to say the extension will stay compatible until Symphony 3 might someday be released.

I guess you could also just release the current code as version `1.0` as the extension seems to work stable, is well documented and (I guess) feature-complete.

Thanks a lot, Roman

**Comment by twiro** [comment]
The release information might look somehow like this...

    <release version="1.0.0" date="2017-02-17" min="2.3.1" max="2.x.x">
         - Improve Compatibility Information (#1)
     </release>

**Comment by domsammut** [comment]
Hey Roman,

Thanks so much for letting me know. I've had it running on my server for quite a while and honestly had forgot that I'd put it up on GitHub. I've bumped it to version one and specified the max attribute in release information.

Cheers
Dom

**Comment by twiro** [comment]
Thank you very much Dom!

One more thing - if you use `1.0.0` instead of "`v1.0.0` for tagging the release at github the [compatibility table on symphonyextensions.com](http://symphonyextensions.com/extensions/freegeoip_service/#compatibility) will actually be able to directly link the release-number to the according release from your github-repo. This comes quite handy - especially if multiple releases with different compatibilities exist.

Don't know if this is really documented anywhere, but I'm planning to write down some best practices regarding symphony's extension-ecosystem in the [symphony extension network](https://github.com/symphonists/symphony-extensions-network) soon - so if you're interested you're welcome to watch that repo for upcoming information.
